public class checkDatatypes {
    public void methodBoolean(){
        Boolean checkBoolean = True;
        system.debug(checkBoolean);
    }

    public void methodInteger(){
        Integer varfirst = 1;
        Integer varsecond = 2;
        
        system.debug(varfirst);
        system.debug(varsecond);
    }

    public void stringmethod(){
        string varname = 'Name';
        string var2name = 'your name';

        system.debug(varname);
        system.debug(var2name);
    }
}