public  class Loops_assignment {
    integer factorialvalue = 1;
public Integer Forloops(Integer n){
    for (integer i =1; i<=n; i++ ) {    
        factorialvalue = factorialvalue * i;
    }
    return factorialvalue;
}

public integer dowhile(Integer n){
    factorialvalue = 1;
    integer a = 1;
    while (a <= n) {
        factorialvalue = factorialvalue * a;
    }   
    return factorialvalue;
} 

}
