public class SetDemo {
    public static void citySet(){
        Set<string> cities = new set<string>();
        cities.add('Tokyo');
        cities.add('Berlin');
        cities.add('Moscow');
        cities.add('Kabul');
        cities.add('Tokyo');
        cities.add('Berlin');
        cities.add('Moscow');
        cities.add('Kabul');
        cities.add('Tokyo');
        cities.add('Berlin');
        cities.add('Moscow');
        cities.add('Kabul');

        system.debug('list of cities ' + cities);

    }
}
